FROM nvidia/cuda:11.7.1-cudnn8-devel-ubuntu22.04

RUN apt-get update && \
    apt-get install -y --allow-unauthenticated \
    build-essential \
    libcurl3-dev \
    libfreetype6-dev \
    libhdf5-serial-dev \
    libzmq3-dev \
    pkg-config \
    rsync \
    software-properties-common \
    sudo \
    zlib1g \
    unzip \
    zip \
    zlib1g-dev \
    wget \
    cmake \
    git \
    curl \
    libssl-dev \
    libcurl4-openssl-dev \
    openjdk-8-jre-headless \
    autoconf \
    automake \
    libtool \
    libffi-dev \
    && apt-get clean && \
    && rm -rf /var/lib/apt/lists/*

#install python
WORKDIR /home/workdir     
RUN wget https://www.python.org/ftp/python/3.8.6/Python-3.8.6.tgz \
    && tar -xzvf Python-3.8.6.tgz \
    && cd Python-3.8.6 \
    && ./configure --prefix=/usr/local/python3 --enable-optimizations \
    && make -j96 \
    && make install 
RUN rm -f /usr/bin/python \
    && rm -f /usr/bin/pip \
    && ln -s /usr/local/python3/bin/python3.8 /usr/bin/python \
    && ln -s /usr/local/python3/bin/pip3 /usr/bin/pip \
    && rm -rf /home/workdir

RUN python -m pip --no-cache-dir install --upgrade \
    "pip<20.3" \
    setuptools==52.0.0

RUN pip install wheel==0.37.1

RUN pip install \
    astor==0.8.1 \
    numpy==1.16.6 && \
    protobuf==3.17.3 && \
    pip install --no-deps \
    keras-preprocessing==1.0.5

# install bazel
WORKDIR /home/workdir

ARG BAZEL_VERSION=0.26.1

RUN wget  -O /home/workdir/installer.sh https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel-${BAZEL_VERSION}-installer-linux-x86_64.sh \
    && wget -O /home/workdir/LICENSE.txt "https://raw.githubusercontent.com/bazelbuild/bazel/master/LICENSE"  \
    && chmod +x /home/workdir/installer.sh \
    && /home/workdir/installer.sh \
    && rm -rf /home/workdir
