# Dockerfile for DLRM training
# Base img
FROM ubuntu:18.04

# copy code & data into container
ADD train_stand.py /root/train_stand.py
ADD data/*.csv /root/data/

RUN mkdir /root/result

# set proxy
# ENV http_proxy=
# ENV https_proxy=

# install python
RUN apt update \
    && apt install python3.6 -y\
    && apt-get install python3-pip -y\
    && ln /usr/bin/python3 /usr/bin/python \
    && ln /usr/bin/pip3 /usr/bin/pip \
    && python -m pip install --upgrade pip

# install tensorflow 1.15
RUN pip install tensorflow==1.15


