FROM nvidia/cuda:11.4.2-cudnn8-devel-ubuntu18.04

RUN apt-get update && \
    apt-get install -y --allow-unauthenticated \
    wget \
    cmake \
    git \
    unzip \
    curl \
    libssl-dev \
    libcurl4-openssl-dev \
    zlib1g-dev \
    python3 \
    python3-dev \
    python3-pip \
    && apt-get clean && \
    ln -sf python3 /usr/bin/python && \
    ln -sf pip3 /usr/bin/pip

RUN pip install \
    astor==0.8.1 \
    numpy==1.16.6 && \
    protobuf==3.17.3 && \
    pip install --no-deps \
    keras-preprocessing==1.0.5
