# Dockerfile for DLRM training
# Base img
FROM ubuntu:18.04

# copy code & data into container
ADD data/* /root/data/
ADD train.py /root/
ADD script/* /root/script/


# install python
RUN apt update \
    && apt install python3.6 -y\
    && apt-get install python3-pip -y\
    && ln /usr/bin/python3 /usr/bin/python \
    && ln /usr/bin/pip3 /usr/bin/pip \
    && python -m pip install --upgrade pip

# install tensorflow 1.15
RUN pip install tensorflow==1.15


