#test image
deeprec_test_image: alideeprec/deeprec-release-modelzoo:latest
tf_test_image: alideeprec/deeprec-weekly-modelzoo:tf

#test model default: [WDL, DLRM ,DeepFM, DSSM, DIEN, DIN]
test_model: 
  - dlrm
  - wide_and_deep
  - deepfm
  - dssm
  - dien
  - din
  - esmm
  - dbmtl
  - mmoe
  - simple_multitask
  - bst
  
#batchsize map<model,batchsize>
model_batchsize:
  wide_and_deep: 512
  dlrm: 512
  deepfm: 512
  dssm: 4096
  dien: 512
  din: 512
  esmm: 512
  dbmtl: 512
  mmoe: 512
  simple_multitask: 512
  bst: 512
  
#args for deeprec
#like --emb_fusion true
modelArgs:

#tf on/off
stocktf: on

# set cpu
cpu_sets:

# set gpu
gpu_sets:

# env config 
env_var:
  - export START_STATISTIC_STEP=100
  - export STOP_STATISTIC_STEP=110

