path: "tensorflow.EmbeddingVariableOption"
tf_class {
  is_instance: "<class \'tensorflow.python.ops.variables.EmbeddingVariableOption\'>"
  is_instance: "<type \'object\'>"
  member_method {
    name: "__init__"
    argspec: "args=[\'self\', \'ht_type\', \'ht_partition_num\', \'evict_option\', \'ckpt\', \'filter_option\', \'storage_option\', \'init_option\'], varargs=None, keywords=None, defaults=[\'\', \'1000\', \'None\', \'None\', \'None\', \'<tensorflow.python.ops.variables.StorageOption object instance>\', \'<tensorflow.python.ops.variables.InitializerOption object instance>\'], "
  }
}
