path: "tensorflow.CounterFilter"
tf_class {
  is_instance: "<class \'tensorflow.python.ops.variables.CounterFilter\'>"
  is_instance: "<type \'object\'>"
  member_method {
    name: "__init__"
    argspec: "args=[\'self\', \'filter_freq\'], varargs=None, keywords=None, defaults=[\'0\'], "
  }
}
