op {
  graph_op_name: "FusedEmbeddingSparsePostLookUp"
  summary: "A fused embedding op, usually using for partitioned and distriuted embedding variables."
  description: <<END
FusedEmbeddingSparsePreLookUp, FusedEmbeddingSparsePostLookUp should be used together.
There should be several Gather ops before this op. The Gather ops gather embedding shards from
embedding variable and this op glue them together, then apply combiner and max_morm according to
embedding indices.
END
}
