#test image
deeprec_test_image: alideeprec/deeprec-release-modelzoo:gpu-latest
tf_test_image: alideeprec/deeprec-release-modelzoo:gpu-latest

#test model
test_model: 
  - dlrm
  - wide_and_deep
  - deepfm
  - dssm
  - dien
  - din
  - esmm
  - dbmtl
  - mmoe
  - simple_multitask
  - bst
  - masknet
  - dcnv2
  - dcn
  - ple
  
#batchsize map<model,batchsize>
model_batchsize:
  wide_and_deep: 32768
  dlrm: 8192
  deepfm: 8192
  dssm: 32768
  dien: 16384
  din: 16384
  esmm: 32768
  dbmtl: 32768
  mmoe: 8192
  simple_multitask: 32768
  bst: 8192
  masknet: 8192
  dcnv2: 8192
  dcn: 8192
  ple: 8192
  
#args for deeprec
#like --emb_fusion true
modelArgs:
  --steps 12000

#tf on/off
stocktf: on

# set cpu
cpu_sets:

# set gpu
gpu_sets: all

# env config 
env_var:
  - export START_STATISTIC_STEP=100
  - export STOP_STATISTIC_STEP=110

