name: GPU Examples Unit Tests

on: 
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'modelzoo/**'
      - 'sparse_operation_kit/**'
      - 'triton/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'modelzoo/**'
      - 'sparse_operation_kit/**'
      - 'triton/**'

env:
  IMAGE: registry.cn-shanghai.aliyuncs.com/pai-dlc-share/deeprec-developer:deeprec-dev-gpu-cibuild-py36-cu110-ubuntu18.04
  JOBNAME: deeprec-ci-gpu-${{ github.run_id }}

jobs:
  build:
    runs-on: [self-hosted, gpu]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    
    - name: Pull Image And Start Container
      if: ${{ success() }}
      run:
        cibuild/pull_image_and_start_container.sh gpu ${IMAGE} ${JOBNAME}

    - name: Upload Source
      run:
        cibuild/upload.sh ${JOBNAME} ../cibuild /mnt

    - name: Unit Test
      if: ${{ always() }}
      run: |-
        docker exec ${JOBNAME} /mnt/cibuild/gpu-ut/gpu-examples-ut.sh /mnt
    
    - name:  Remove Container
      if: ${{ always() }}
      run: 
        cibuild/remove_container.sh ${JOBNAME}