name: CPU Tests

on: workflow_dispatch #[push, pull_request]

env:
  IMAGE: registry.cn-shanghai.aliyuncs.com/pai-dlc/deeprec:developer-ubuntu18.04-py3.6
  JOBNAME: deeprec-ci-cpu-${{ github.run_id }}
  PODNAME: deeprec-ci-cpu-${{ github.run_id }}-chief-0
  BAZEL_CACHE: ${{ secrets.BAZEL_CACHE }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: PAI DLC
    steps:
    - name: Setup Environment
      uses: aliyun/ack-set-context@v1
      with:
        access-key-id: "${{ secrets.ACCESS_KEY_ID }}"
        access-key-secret: "${{ secrets.ACCESS_KEY_SECRET }}"
        cluster-id: "${{ secrets.ACK_CLUSTER_ID }}"
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Install Pod
      run: |-
        helm install ${JOBNAME} cibuild/ --set image=${IMAGE}
    - name: Upload Source
      run: |-
        cibuild/upload.sh ${PODNAME} ../cibuild
    - name: Build Wheel
      run: |-
        kubectl exec -it ${PODNAME} -- cibuild/build-cpu.sh
    - name: Uninstall Pod
      run: |-
        helm uninstall ${JOBNAME}

