name: CPU Examples Unit Tests

on: 
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'modelzoo/**'
      - 'sparse_operation_kit/**'
      - 'triton/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'modelzoo/**'
      - 'sparse_operation_kit/**'
      - 'triton/**'

env:
  IMAGE: registry.cn-shanghai.aliyuncs.com/pai-dlc-share/deeprec-developer:deeprec-dev-cpu-cibuild-py36-ubuntu18.04
  JOBNAME: deeprec-ci-cpu-${{ github.run_id }}
  PODNAME: deeprec-ci-cpu-${{ github.run_id }}-chief-0
  BAZEL_CACHE: ${{ secrets.BAZEL_CACHE }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: PAI DLC
    steps:
    - name: Setup Environment
      uses: aliyun/ack-set-context@v1
      with:
        access-key-id: "${{ secrets.ACCESS_KEY_ID }}"
        access-key-secret: "${{ secrets.ACCESS_KEY_SECRET }}"
        cluster-id: "${{ secrets.ACK_CLUSTER_ID }}"
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Install Pod
      timeout-minutes: 360
      run: |-
        helm install ${JOBNAME} cibuild/ --set image=${IMAGE} --timeout 1h
    - name: Upload Source
      if: ${{ always() }}
      run: |-
        cibuild/upload.sh ${PODNAME} ../cibuild
    - name: Unit Test
      if: ${{ always() }}
      run: |-
        kubectl exec -it ${PODNAME} -- cibuild/cpu-ut/cpu-examples-ut.sh
    - name: Uninstall Pod
      if: ${{ always() }}
      run: |-
        helm uninstall ${JOBNAME}
