name: GPU Build Wheel

on: 
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'modelzoo/**'
      - 'sparse_operation_kit/**'
      - 'triton/**'
  pull_request_review:
    types: [submitted]
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'modelzoo/**'
      - 'sparse_operation_kit/**'
      - 'triton/**'

env:
  IMAGE: registry.cn-shanghai.aliyuncs.com/pai-dlc-share/deeprec-developer:deeprec-dev-gpu-cibuild-py36-cu110-ubuntu18.04
  JOBNAME: deeprec-ci-gpu-${{ github.run_id }}

jobs:
  build:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'push' || (github.event_name == 'pull_request_review' && github.event.review.state == 'approved') }}
    runs-on: [self-hosted, gpu]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    
    - name: Pull Image And Start Container
      run:
        cibuild/pull_image_and_start_container.sh gpu ${IMAGE} ${JOBNAME}
    
    - name: Upload Source
      run:
        cibuild/upload.sh ${JOBNAME} ../cibuild /mnt

    - name: Build Wheel
      run:
        docker exec ${JOBNAME} /mnt/cibuild/build-cpu.sh /mnt

    - name:  Remove Container
      if: ${{ always() }}
      run: 
        cibuild/remove_container.sh ${JOBNAME}

